labs/labk3s/README.md
labs/labk3s/createInstances.sh
labs/labk3s/deleteInstances.sh
labs/labk3s/import.sh
labs/labk3s/keypair/provider.tf
labs/labk3s/keypair/resource.tf
labs/labk3s/ovhrc.template
labs/labk3s/properties
labs/labk3s/utils/ovhAPI.sh
labs/labk3s/variables.tf

Add basics reference to initiate the lab
Add keypair admin terrafomr resource
Update scripts according new config file location
Add properties files to manage lab parameters

Basics add

---

basics/README.md

Refacto basics

---

networking/private-network-mono-region/README.md
networking/private-network-mono-region/data.tf
networking/private-network-mono-region/outputs.tf
networking/private-network-mono-region/providers.tf
networking/private-network-mono-region/resources.tf
networking/private-network-mono-region/variables.auto.tfvars
networking/private-network-mono-region/variables.tf

Split vars

---

databases/mongodb/README.md

Update README.md - Typo

---

databases-analytics/databases/postgresql-tf/README.md
databases-analytics/databases/postgresql-tf/my-ovh_postgresql_db.tf
databases-analytics/databases/postgresql-tf/my-provider.tf
databases-analytics/databases/postgresql-tf/my-variables.tf
databases-analytics/databases/postgresql-tf/output.tf

The goal of this PR is to add an example on how create a managed PostgreSQL in an OVHcloud public cloud project with Terraform.

feat: 💿 PostgreSQL with TF

---

containers-orchestration/managed-kubernetes/autoscaler/.dockerignore
containers-orchestration/managed-kubernetes/autoscaler/Dockerfile
containers-orchestration/managed-kubernetes/autoscaler/README.md
containers-orchestration/managed-kubernetes/autoscaler/cpu-load.py
containers-orchestration/managed-kubernetes/autoscaler/cpu-load.yml

Demo code to illustrate the MKS autoscaler feature

feat: ✨ Mks autoscaler demo

---

.gitignore
ai/ai-endpoints/js-langchain-chatbot/README.md
ai/ai-endpoints/js-langchain-chatbot/chatbot.js
ai/ai-endpoints/js-langchain-chatbot/package-lock.json
ai/ai-endpoints/js-langchain-chatbot/package.json

Blocking chatbot with LangChainJs example

feat: ✨ V1 JS chatbot

---

ai/ai-endpoints/README.md

Add a README to AI Endpoints demos

doc: 📝 add README file to AI endpoints demos

---

.gitignore
databases-analytics/databases/kafka-basics/README.md
databases-analytics/databases/kafka-basics/python/consumer.py
databases-analytics/databases/kafka-basics/python/producer.py
databases-analytics/databases/kafka-basics/python/readme.md
databases-analytics/databases/kafka-basics/python/requirements.txt

first of a serie of kafka example

add basics python kafka example

---

ai/ai-endpoints/python-langchain-chatbot/README.md
ai/ai-endpoints/python-langchain-chatbot/chat-bot-streaming-rag.py
ai/ai-endpoints/python-langchain-chatbot/rag-files/content.txt
ai/ai-endpoints/python-langchain-chatbot/requirements.txt

First version of a RAG example with AI Endpoints

feat: ✨ V1 for RAG + AI Endpoints + LangChain + Python

---

ai/ai-endpoints/java-langchain4j-chatbot/src/main/java/com/ovhcloud/examples/aiendpoints/BlockingChatbot.java
ai/ai-endpoints/java-langchain4j-chatbot/src/main/java/com/ovhcloud/examples/aiendpoints/MemoryStreamingChatbot.java
ai/ai-endpoints/python-langchain-chatbot/README.md
ai/ai-endpoints/python-langchain-chatbot/chat-bot-streaming-rag.py
ai/ai-endpoints/python-langchain-chatbot/chat-bot-streaming.py
ai/ai-endpoints/python-langchain-chatbot/chat-bot.py

feat: ✨ Examples review

---

ai/ai-endpoints/README.md
ai/ai-endpoints/java-langchain4j-chatbot/pom.xml
ai/ai-endpoints/java-langchain4j-chatbot/src/main/java/com/ovhcloud/examples/aiendpoints/RAGStreamingChatbot.java

As the OVHcloud AI Endpoints embedding endpoints are available in LangChain4j, I've updated the demo with the official client.

feat: ✨ Use OVHcloud AI Endpoints for embeddings

---

ai/ai-endpoints/java-langchain4j-chatbot/pom.xml
ai/ai-endpoints/java-langchain4j-chatbot/src/main/java/com/ovhcloud/examples/aiendpoints/RAGStreamingChatbot.java

Replace the in-memory store by a PG Vector and use our managed PG instance

feat: ✨ Use PG managed instance to store embeddings

---

ai/ai-endpoints/README.md

add the new notebooks path on the AI Endpoints README

Update README.md with ASR and TTS tutorials

---

ai/ai-endpoints/java-langchain4j-chatbot/src/main/java/com/ovhcloud/examples/aiendpoints/RAGStreamingChatbot.java

fix: 🐛 fix #76, java.nio.file.InvalidPathException

---

containers-orchestration/managed-kubernetes/create-cluster-in-private-network-tf/README.md
containers-orchestration/managed-kubernetes/create-cluster-in-private-network-tf/ovh_kube_cluster_private.tf
containers-orchestration/managed-kubernetes/create-cluster-in-private-network-tf/provider.tf
containers-orchestration/managed-kubernetes/create-cluster-in-private-network-tf/variables.tf

Create a concrete example deploying a MKS inside a private network (inside a vRack attached to the public cloud project).
Fully deployable through the OVh Terraform provider (not openstack!).

Deploy a MKS inside a private network (vRack and attachment included)

---

.github/release.yml

Proposal for new categories in the automatic release note generation

conf: ⚙️ Update release note configuration

---

README.md
storage/README.md
storage/s3-with-tf/README.md
storage/s3-with-tf/create-s3-buckets.tf
storage/s3-with-tf/output.tf
storage/s3-with-tf/provider.tf
storage/s3-with-tf/variables.tf

This PR is to illustrate how to create an OVHcloud object container storage.

feat: 📀 Add S3 creation example

---

storage/s3-with-tf/README.md
storage/s3-with-tf/provider.tf
storage/s3-with-tf/variables.tf

This PR adds the region in variables and explain how to know the list of existing regions

[S3 example] feat: add the region in variables

---

.gitignore
containers-orchestration/managed-kubernetes/use-image-from-registry/README.md
containers-orchestration/managed-kubernetes/use-image-from-registry/overlays/progmag/deployment.yaml
containers-orchestration/managed-kubernetes/use-image-from-registry/overlays/progmag/kustomization.yaml

For the magazine programmez I updated the existing example to add a kustomize layer.

Add a new kustomize layer for programmez magazine example

---

ai/rock-paper-scissors/application/Dockerfile
ai/rock-paper-scissors/training/README.md
ai/rock-paper-scissors/training/train.py

Upgrade the Rock / Paper / Scissors demo with YOLOv11 and fix minor typos

Update training rock paper scisors

---

.gitignore
containers-orchestration/managed-rancher/create-rancher-with-tf/README.md
containers-orchestration/managed-rancher/create-rancher-with-tf/create.sh
containers-orchestration/managed-rancher/create-rancher-with-tf/destroy.sh
containers-orchestration/managed-rancher/create-rancher-with-tf/output.tf
containers-orchestration/managed-rancher/create-rancher-with-tf/provider.tf
containers-orchestration/managed-rancher/create-rancher-with-tf/rancher.tf
containers-orchestration/managed-rancher/create-rancher-with-tf/variables.tf.template

This PR adds an example that deploys a Rancher and output useful information (URL and bootstrap password)
Adds a new example that show how to create a Rancher with Terraform.
Useful for automation.

Add new example create rancher with TF

---

storage/s3-with-tf/README.md
storage/s3-with-tf/create-s3-buckets.tf
storage/s3-with-tf/output.tf
storage/s3-with-tf/provider.tf
storage/s3-with-tf/variables.tf
storage/s3-with-tf/variables.tf.template

Now we can deploy/create s3 compatible containers/bucket with the OVHcloud terraform provider.
Ànd this demo also shows how to create one bucket in 1-AZ region and one bucket in 3-AZ region.

Deploy Object Storage containers with OVHcloud TF provider

---

ai/ai-endpoints/audio-summarizer-assistant/README.md
ai/ai-endpoints/audio-summarizer-assistant/audio-summarizer-app.py
ai/ai-endpoints/audio-summarizer-assistant/requirements.txt
ai/ai-endpoints/audio-virtual-assistant/README.md
ai/ai-endpoints/audio-virtual-assistant/audio-virtual-assistant-app.py
ai/ai-endpoints/audio-virtual-assistant/requirements.txt
ai/ai-endpoints/python-langchain-conversational-memory/README.md
ai/ai-endpoints/python-langchain-conversational-memory/chatbot-memory-langchain.ipynb
ai/ai-endpoints/python-langchain-conversational-memory/requirements.txt

3 AI Endpoints tutorials fixed for GA
Fix done on AI Endpoints tutorials:
- Fix Python dependencies versions
- Replace deprecated models

Fix AI Endpoints tutorials

---

ai/ai-endpoints/README.md
ai/ai-endpoints/structured-output-langchain4j/README.md
ai/ai-endpoints/structured-output-langchain4j/SimpleStructuredOutput.java

Simple example on how to use structured output with AI Endpoints.
The demo uses JBang.

feat: ✨ simple example for structured output

---

ai/ai-endpoints/audio-summarizer-assistant/requirements.txt

fix Gradio version for audio summarizer demo

fix: 🐛 gradio version for audio summarizer

---

ai/ai-endpoints/README.md
ai/ai-endpoints/car-damage-verification-using-vlm/README.md
ai/ai-endpoints/car-damage-verification-using-vlm/chainlit.md
ai/ai-endpoints/car-damage-verification-using-vlm/requirements.txt
ai/ai-endpoints/car-damage-verification-using-vlm/test_vision_connection.py
ai/ai-endpoints/car-damage-verification-using-vlm/verification_app.py
ai/ai-endpoints/car-damage-verification-using-vlm/verification_demo.py

This demo showcases Vision Language Model capabilities for car damage verification using OVHcloud AI Endpoints. Features include:
- Interactive Chainlit web application
- Multi-image analysis with Qwen2.5-VL-72B-Instruct
- Car claim verification (manufacturer, model, color, damage)
- Refactored code with ~30% complexity reduction
- Comprehensive documentation and setup guide
This PR adds a comprehensive Vision Language Model (VLM) demonstration that showcases real-world AI applications using OVHcloud AI Endpoints. The demo allows users to make claims about their car and then verify those claims against uploaded photos using advanced computer vision.
**What's included:**
- Complete interactive web application built with Chainlit
- Core verification engine using Qwen2.5-VL-72B-Instruct …

Add VLM car damage verification demo

---

ai/ai-endpoints/README.md
ai/ai-endpoints/function-calling-langchain4j/ImageGeneration.java
ai/ai-endpoints/function-calling-langchain4j/README.md

This PR is the code to illustrate how to do function calling with AI Endpoints.
The chosen example is how to generate images with Stable Diffusion XL by optimizing the prompt with a LLM and call the SDXL model in a tool.

feat: 🖼️ SDXL prompt optimizer feature

---

.gitignore
ai/llm-fine-tune/README.md
ai/llm-fine-tune/chatbot/Dockerfile
ai/llm-fine-tune/chatbot/chatbot.py
ai/llm-fine-tune/chatbot/requirements.txt
ai/llm-fine-tune/dataset/DatasetAugmentation.py
ai/llm-fine-tune/dataset/DatasetCreation.py
ai/llm-fine-tune/notebook/axolto-llm-fine-tune-Meta-Llama-3.2-1B-instruct-ai-endpoints.ipynb
ai/llm-fine-tune/notebook/instruct-lora-1b-ai-endpoints.yml
ai/llm-fine-tune/requirements.txt

Complete tutorial on how fine tune a LLama 3.2 1B model with AI Machine Learning Services

Llm fine tune

---

ai/ai-endpoints/asr-features/tutorial-asr-diarization.ipynb

Here is a new replacement of RIVA by Whisper and its diarization feature.
To be honest, i had to trick the display of diarization's result to make it work with current audio. I think since it's a very short audio file, the new diarization feature is struggling with identifying two different speakers. 
This new code should work with longer audio files, but "it's not" with the provided example audio file, as the diarization sees only one person.

replace riva by whisper model and diarization
